// Package intent provides a deterministic natural-language command layer over GoKit interpreters.
package intent

import("fmt";"regexp";"strings";"time";"github.com/codedbyhassan/gokit/age";"github.com/codedbyhassan/gokit/calculator";"github.com/codedbyhassan/gokit/interpret";"github.com/codedbyhassan/gokit/interpret/date";"github.com/codedbyhassan/gokit/interpret/expression";"github.com/codedbyhassan/gokit/interpret/number";"github.com/codedbyhassan/gokit/interpret/unit";"github.com/codedbyhassan/gokit/units")
type Kind string
const(Calculate Kind="calculate";Convert Kind="convert";Age Kind="age")
type Result struct{Kind Kind;Value any;OriginalInput string;Format string;Confidence interpret.Confidence;Assumptions []string}
var quantityExpressionPattern=regexp.MustCompile(`^(.+?)\s+(plus|minus)\s+(.+)$`);var agePattern=regexp.MustCompile(`^how old is(?: someone)?(?: born)?\s+(.+)$`)
func Parse(input string)(Result,error){return ParseAt(input,time.Now())}
func ParseAt(input string,asOf time.Time)(Result,error){original:=input;clean:=normalize(input);if clean==""{return Result{OriginalInput:original},interpret.ErrEmptyInput};if m:=agePattern.FindStringSubmatch(clean);len(m)==2{birth,e:=date.Parse(m[1]);if e!=nil{return Result{OriginalInput:original},fmt.Errorf("invalid birth date: %w",e)};v,e:=age.Calculate(birth.Value,asOf);if e!=nil{return Result{OriginalInput:original},e};return Result{Kind:Age,Value:v,OriginalInput:original,Format:"age request",Confidence:.99},nil};if looksLikeConversion(clean){parsed,e:=unit.Parse(clean);if e==nil{return Result{Kind:Convert,Value:parsed.Value,OriginalInput:original,Format:"conversion request",Confidence:.99};if strings.HasPrefix(clean,"convert ")||strings.HasPrefix(clean,"please convert "){return Result{OriginalInput:original},e}};clean=stripCommandPrefix(clean);if _,e:=number.Parse(clean);e==nil{return Result{OriginalInput:original},interpret.ErrUnrecognizedInput};if node,e:=expression.ParseQuantityAST(clean);e==nil{if q,ee:=expression.EvaluateQuantity(node);ee==nil&&q.Unit.Name!=""{return Result{Kind:Calculate,Value:calculator.Result{Value:q.Value,Operation:calculator.Add},OriginalInput:original,Format:"quantity expression",Confidence:.99},nil}};if m:=quantityExpressionPattern.FindStringSubmatch(clean);len(m)==4{if r,e:=calculateQuantities(m[1],m[2],m[3],original);e==nil{return r,nil}};if parsed,e:=expression.Parse(clean);e==nil{calculated,e:=expression.Calculate(clean);if e!=nil{return Result{OriginalInput:original},e};return Result{Kind:Calculate,Value:calculated,OriginalInput:original,Format:parsed.Format,Confidence:parsed.Confidence},nil};return Result{OriginalInput:original},fmt.Errorf("%w: %q",interpret.ErrUnrecognizedInput,input)}
func normalize(input string)string{clean:=strings.ToLower(strings.TrimSpace(input));clean=strings.TrimSuffix(clean,"?");clean=strings.Replace(clean,"what's ","what is ",1);return strings.Join(strings.Fields(clean)," ")}
func stripCommandPrefix(input string)string{for _,p:=range []string{"please calculate ","calculate ","what is ","please work out ","work out "}{if strings.HasPrefix(input,p){return strings.TrimSpace(strings.TrimPrefix(input,p))}};return input}
func looksLikeConversion(input string)bool{return strings.HasPrefix(input,"convert ")||strings.HasPrefix(input,"please convert ")||strings.Contains(input," to ")||strings.Contains(input," into ")||strings.Contains(input," in ")}
func calculateQuantities(l,o,r,original string)(Result,error){left,e:=parseQuantity(l);if e!=nil{return Result{},e};right,e:=parseQuantity(r);if e!=nil{return Result{},e};if left.Unit.Dimension!=right.Unit.Dimension{return Result{},fmt.Errorf("cannot %s %s and %s",o,left.Unit.Name,right.Unit.Name)};rv,e:=units.Convert(right.Value,right.Unit,left.Unit);if e!=nil{return Result{},e};op:=calculator.Add;if o=="minus"{op=calculator.Subtract};v,e:=calculator.Calculate(left.Value,rv,op);if e!=nil{return Result{},e};return Result{Kind:Calculate,Value:v,OriginalInput:original,Format:"quantity calculation",Confidence:.99,Assumptions:[]string{fmt.Sprintf("converted %s to %s before arithmetic",right.Unit.Symbol,left.Unit.Symbol)}},nil}
func parseQuantity(input string)(unit.Quantity,error){p,e:=unit.Parse(strings.TrimSpace(input));if e!=nil{return unit.Quantity{},e};q,ok:=p.Value.(unit.Quantity);if !ok{return unit.Quantity{},fmt.Errorf("expected a quantity, got %T",p.Value)};return q,nil}
