// Package number interprets human-friendly numeric input into float64 values.
package number

import("fmt";"math";"regexp";"strconv";"strings";"github.com/codedbyhassan/gokit/interpret")
var numeric=regexp.MustCompile(`^[+-]?(?:\d+(?:\.\d+)?|\.\d+)$`)
var scaleWords=map[string]float64{"thousand":1e3,"million":1e6,"billion":1e9,"trillion":1e12,"quadrillion":1e15}
var wordNumbers=map[string]float64{"zero":0,"one":1,"two":2,"three":3,"four":4,"five":5,"six":6,"seven":7,"eight":8,"nine":9,"ten":10,"eleven":11,"twelve":12,"thirteen":13,"fourteen":14,"fifteen":15,"sixteen":16,"seventeen":17,"eighteen":18,"nineteen":19,"twenty":20,"thirty":30,"forty":40,"fifty":50,"sixty":60,"seventy":70,"eighty":80,"ninety":90}
func Parse(input string)(interpret.Result[float64],error){original:=input;clean:=normalize(input);if clean==""{return interpret.Result[float64]{OriginalInput:original},interpret.ErrEmptyInput};if numeric.MatchString(clean){v,e:=strconv.ParseFloat(clean,64);if e==nil&&!math.IsNaN(v)&&!math.IsInf(v,0){return result(v,"numeric",interpret.HighConfidence,original),nil}};if v,ok:=parseSuffixed(clean);ok{return result(v,"scaled numeric",.98,original),nil};if v,f,ok:=parseWords(clean);ok{return result(v,f,.96,original),nil};return interpret.Result[float64]{OriginalInput:original},fmt.Errorf("%w: %q",interpret.ErrUnrecognizedInput,input)}
func normalize(input string)string{s:=strings.ToLower(strings.TrimSpace(input));s=strings.ReplaceAll(s,"_","");s=strings.ReplaceAll(s,",","");s=strings.ReplaceAll(s,"–","-");s=strings.ReplaceAll(s,"—","-");return strings.Join(strings.Fields(s)," ")}
func result(v float64,f string,c interpret.Confidence,o string)interpret.Result[float64]{return interpret.Result[float64]{Value:v,Format:f,Confidence:c,OriginalInput:o}}
func parseSuffixed(input string)(float64,bool){neg:=false;if strings.HasPrefix(input,"-"){neg=true;input=strings.TrimSpace(input[1:])}else if strings.HasPrefix(input,"+"){input=strings.TrimSpace(input[1:])};if m:=regexp.MustCompile(`^(.+?)\s+(thousand|million|billion|trillion|quadrillion)$`).FindStringSubmatch(input);len(m)==3{base:=m[1];v,ok:=parseBase(base);if ok{if neg{v=-v};return v*scaleWords[m[2]],true}};parts:=strings.Fields(input);if len(parts)<2{return 0,false};var total float64;var group []string;lastScale:=math.Inf(1);found:=false;for _,p:=range parts{if scale,ok:=scaleWords[p];ok{if scale>=lastScale||len(group)==0{return 0,false};v,ok:=parseBase(strings.Join(group," "));if !ok{return 0,false};total+=v*scale;group=nil;lastScale=scale;found=true}else{group=append(group,p)}};if !found{return 0,false};if len(group)>0{v,ok:=parseBase(strings.Join(group," "));if !ok{return 0,false};total+=v};if neg{total=-total};return total,true}
func parseBase(s string)(float64,bool){s=strings.TrimSpace(s);if numeric.MatchString(s){v,e:=strconv.ParseFloat(s,64);return v,e==nil};v,_,ok:=parseWords(s);return v,ok}
func parseWords(input string)(float64,string,bool){parts:=strings.Fields(strings.ReplaceAll(input,"-"," "));if len(parts)==0{return 0,"",false};neg:=false;if parts[0]=="minus"||parts[0]=="negative"{neg=true;parts=parts[1:]};if len(parts)==0{return 0,"",false};if p:=indexOfPoint(parts);p>=0{if p==0||p==len(parts)-1{return 0,"",false};whole,ok:=parseIntegerWords(parts[:p]);if !ok{return 0,"",false};frac:="";for _,t:=range parts[p+1:]{if v,ok:=wordNumbers[t];ok&&v<=9{frac+=strconv.Itoa(int(v))}else if numeric.MatchString(t)&&!strings.Contains(t,"."){frac+=t}else{return 0,"",false}};f,e:=strconv.ParseFloat("0."+frac,64);if e!=nil{return 0,"",false};v:=whole+f;if neg{v=-v};return v,"number words",true};v,ok:=parseIntegerWords(parts);if !ok{return 0,"",false};if neg{v=-v};return v,"number words",true}
func indexOfPoint(parts []string)int{for i,t:=range parts{if t=="point"||t=="dot"{return i}};return -1}
func parseIntegerWords(parts []string)(float64,bool){if len(parts)==0{return 0,false};var total,group float64;used:=false;lastScale:=math.Inf(1);lastTens:=false;hundred:=false;for _,t:=range parts{if t=="and"{continue};if v,ok:=wordNumbers[t];ok{if lastTens{return 0,false};group+=v;lastTens=v>=20&&v<=90&&math.Mod(v,10)==0;used=true;continue};if t=="hundred"{if group<=0||hundred{return 0,false};group*=100;hundred=true;lastTens=false;used=true;continue};if scale,ok:=scaleWords[t];ok{if group<=0||scale>=lastScale{return 0,false};total+=group*scale;group=0;hundred=false;lastTens=false;lastScale=scale;used=true;continue};return 0,false};if !used{return 0,false};return total+group,true}
func parseAtomicNumber(s string)(float64,error){if numeric.MatchString(s){return strconv.ParseFloat(s,64)};if v,_,ok:=parseWords(s);ok{return v,nil};return 0,fmt.Errorf("not a number")}
